config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #list
  get "tasks", to: "tasks#index", as: "task_index"

  #create
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  #read
  get "tasks/:id", to: "tasks#show", as: "task"

  #update
  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch "tasks/:id", to: "tasks#update"

  #delete
  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_index_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>

<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>


<% @tasks.each do |task| %>
<ul>
  <li>

  <% if task.completed == true %>
  <i class="far fa-check-circle"></i>
  <% else %>
  <i class="far fa-circle"></i>
  <% end %>
  <%= link_to(task.title.upcase, task_path(task.id)) %>
  <br>
  <i class="far fa-edit"></i>
  <%= link_to("edit", task_edit_path(task.id)) %>
  <i class="far fa-trash-alt"></i>
  <%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  </li>

</ul>
<% end %>

<%= link_to("Add a new task", tasks_new_path) %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>

  <%= link_to("Back to list", task_index_path(@task)) %>

  <%= link_to("Edit this task", task_edit_path(@task))%>